version: '2'
services:
    kafka:
        container_name: liligo-kafka
        image: spotify/kafka
        restart: always
        environment:
          - ADVERTISED_HOST=127.0.0.1
          - ADVERTISED_PORT=9092
        ports:
          - "9092:9092"
          - "2181:2181"
        logging:
          options:
            max-size: 1G

    producer:
        container_name: liligo-producer
        image: lilidata/kafka-python-producer
        restart: always
        environment:
          - KAFKA=127.0.0.1
          - KAFKAPORT=9092
          - TOPIC=test
        logging:
          options:
            max-size: 1G
        network_mode: "host"
        entrypoint: python producer.py
